<h1>Registration Form</h1>

<form action="?" method="POST">
    <label for="firstName">First Name:</label>
    <input type="text" name="firstName" id="firstName" maxlength="50" size="20"/><br/>
    <label for="lastName">Last Name:</label>
    <input type="lastName" name="lastName" id="lastName" maxlength="50" size="20"/><br/>
    <label for="userName">User Name:</label>
    <input type="text" name="userName" id="userName" maxlength="50" size="20"/><br/>
    <label for="password">Password:</label>
    <input type="password" name="password" id="password" maxlength="40" size="20"/><br/>
    <input type="submit" class="logout" value="Submit"/>
</form>

<a href="index.php" class="user">Back</a>